### ISSUE TITLE
Denis - Configurar o Docker Compose para o container de armazenamento.

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#10]

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/cbe7c8fd-87de-4eee-bb90-c7f2bdc2eb91)

Criação docker-compose completa, parâmetros do samba de usuário e senha podem ser modificados posteriormente com intuito de segurança. Volume Samba criado apenas para testar o funcionamento do serviço.
