### ISSUE TITLE
Joan - Implementar a lógica de agendamento

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#12]

**Comment by JoanMateus** [comment]
Utilizando o agendamento de tarefas cron para executar o script.

FROM python:3.9-slim

WORKDIR /app

COPY MySQL_Script.py /app

CMD ["python", "MySQL_Script.py"]

RUN apt-get update && apt-get install -y cron

RUN echo "0 3 * * * /usr/local/bin/python /app/script_backup.py >> /var/log/cron.log 2>&1" > /etc/cron.d/backup

CMD cron && tail -f /var/log/cron.log
