### ISSUE TITLE
Denis - Criar Dockerfile para o container de agendamento.

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#14]

**Comment by DenisSSell** [comment]
Criação da pasta docker_agendamento, que nela estará o dockerfile relacionado ao agendamento de tarefas, além de um script de testes apenas para essa etapa e um arquivo crontab que contem o agendamento de tarefas, apenas para testes no momento. Nesse container Docker, será utilizado o sistema operacional do Debian mais atualizado. Será instalado para o agendamento o cron, que executará as tarefas. Foi instalado tambem o porcps apenas para testes de funcionamento para ter noção de quanto tempo demorou para ter a execução do script.

![image](https://github.com/user-attachments/assets/5f9a9fd3-c947-4b57-a57d-bcdd1a026e7c)

**Comment by DenisSSell** [comment]
Dento do arquivo Dockerfile temos a configuração do ambiente do container que fará a tarefa de executar os scripts de backup agendados.

![image](https://github.com/user-attachments/assets/65d9a4fa-5d83-4f9f-b260-2c75ac41af05)

Os comandos iniciais se referem a instalação do cron para o agendamento de tarefas, e o pocps para ter o comando uptime, que fornece uma exibição de uma linha das seguintes informações. O tempo atual, a quanto tempo o sistema está funcionando, quantos usuários estão conectados no momento e as médias de carga do sistema nos últimos 1, 5 e 15 minutos. Foi utilizado no momento apenas para testes, tem chances de ser uma ideia que não será passada a frente.

![image](https://github.com/user-attachments/assets/87646705-6226-4428-9246-f31dbcec49ba)

Em seguida é criado o diretório que recebera os scripts, que no momento recebeu apenas um teste para ver o funcionamento do agendamento. Sendo em seguida copiado os arquivos, sendo eles o do script e o do crontab (o qual contem o agendamento) e dado as permissões necessárias para que haja execução, tanto do agendamento quanto do script

![image](https://github.com/user-attachments/assets/7871f8fb-37d1-474a-9277-c5db85b465d7)

E finalizando temos comando que faz a inicialização do serviço cron, junto com uma leitura das ultimas atualizações do arquivo cron.log
 
![image](https://github.com/user-attachments/assets/11ddc9c3-c1f9-47cf-a36d-4d2326ca0f8d)

**Comment by DenisSSell** [comment]
Dento do arquivo crontab, temos um agendamento simples no momento apenas para ver o funcionamento do container. Nele contendo a tarefa de executar de minuto em minuto um echo apenas para mostrar que teve funcionamento e em seguida rodar o script de teste de funcionamento. Tudo sempre direcionado ao arquivo cron.log localizado no diretório /var/log .

![image](https://github.com/user-attachments/assets/b7d97eaf-d075-438a-bbc2-aacee3b32dfb)

**Comment by DenisSSell** [comment]
Como dito antes, foi criado um script simples e básico apenas para o teste de funcionamento do container. Nele contendo apenas o comando uptime, que foi explicado acima qual a funcionalidade dele, e um simples echo com intuito de mostrar que o teste foi funcional.

![image](https://github.com/user-attachments/assets/89c819d9-fe66-4c97-a0f2-31aa858b6473)
