### ISSUE TITLE
Denis - Configurar scripts para inserir dados de teste nos bancos de dados.

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#16]

**Comment by DenisSSell** [comment]
Inicio da configuração do arquivo Docker Compose

![image](https://github.com/user-attachments/assets/0c97b34d-d36c-4a03-b7ab-967850aced24)

Container worker e agendamento estao comentandos para caso haja modificações. Imagem do container worker vai ser criado e refinado. Assim como o de agendamento que talvez sai

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/4ea5ff32-1720-48b2-af4b-be1d7bdc4696)

Configuração por cima dos container dos bancos de dados MySQL e PostgreSQL.

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/cbe7cada-fd96-4d85-9c60-aaa0d1f0aefb)

Volumes e networks que sarão utilizadas na hora da execução dos containers

**Comment by DenisSSell** [comment]
Buscando mais conhecimento de como funciona a interligação dos containers através do docker compose

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/e33e9c62-d663-4d7e-93d3-89ad8b9ac7f7)

Containers subindo em conjunto

**Comment by DenisSSell** [comment]
Ambos containers dentro da mesma rede, tendo IPs seguidos juntos um atrás do outro

![image](https://github.com/user-attachments/assets/dee35776-3aeb-434b-9dd3-6de01bba28b3)

![image](https://github.com/user-attachments/assets/f7b44282-3888-48a2-a673-a5ad45ae2522)

**Comment by DenisSSell** [comment]
Da mesma forma o container nginx está em funcionamento na porta 8080

![image](https://github.com/user-attachments/assets/943453b0-d7f0-491b-ab66-b6fe243688f8)

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/0e6c42f8-71e1-4873-97f9-8621738ee987)


Script que colocará dados dentro do banco PostgreSQL

O arquivo init.sql possui a execução de comandos para inserir valores a tabelas

![image](https://github.com/user-attachments/assets/10d18f78-f71a-45f4-ae88-912fffc1381e)

**Comment by DenisSSell** [comment]
![image](https://github.com/user-attachments/assets/a7af9313-93dd-4d09-a811-554369c26d5b)

Docker compose fará a execução do script na criação do container
