### ISSUE TITLE
Joan - Revisar o código e refatorar partes necessárias.

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#18]

**Comment by JoanMateus** [comment]
Revisão do script da Worker, foi ajustado algumas informações no arquivo de dado do banco e na leitura do arquivo da Worker necessários para a implementação de agendamento de backups, o Dockerfiler teve algumas alterações para seu funcionamento em relação aos tratamentos de erro que estavam apresentando.

**Comment by JoanMateus** [comment]
Imagem referente ao arquivo de dados que teve a sua formatação alterada sendo acrescentado os dados de data com hora e dia da semana de agendamento.  
![image](https://github.com/user-attachments/assets/668f6fe1-c54f-44aa-ae3b-3ed1918977dc)

**Comment by JoanMateus** [comment]
Imagem referente ao Worker, apresenta as alterações que foram feitas para a leitura do novo formato do arquivo dados.txt e acrescentado a função de agendamento. 
![image](https://github.com/user-attachments/assets/f394e8c2-aa8b-4ecf-b653-88978b782214)
