### ISSUE TITLE
Joan -  Implementar a lógica de backup para MySQL

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#6]

**Comment by JoanMateus** [comment]
Foi implementada a logica do backup MySQL com a linguagem python.

import mysql.connector
import os
import datetime

DB_USER = 'root'
DB_PASSWORD = ''
DB_HOST = 'localhost'
DB_NAME = 'ficha'

BACKUP_FILE = '/diretorio_backup/arqbk.sql'

def realizar_backup():
    try:
        conn = mysql.connector.connect(
            user=DB_USER,
            password=DB_PASSWORD,
            host=DB_HOST,
            database=DB_NAME
        )
        dump_command = f"mysqldump --user={DB_USER} --password={DB_PASSWORD} --host={DB_HOST} {DB_NAME} > {BACKUP_FILE}"
        print(f"Backup realizado com sucesso: {BACKUP_FILE}")

    finally:
        if conn.is_connected():
            conn.close()

if __name__ == '__main__':
    realizar_backup()
