### ISSUE TITLE
Joan - Criar arquivo que será utilizado no worker para backup.

### ISSUE THREAD

**Issue by Nod17** [JoanMateus/Automacao-Backup-Banco-de-dados-#9]

**Comment by JoanMateus** [comment]
Arquivo inicial para criação do Worker, no qual o arquivo realizara os backups dos respectivos banco com base no dados definidos nos arquivos de informações.
![image](https://github.com/user-attachments/assets/12b0fde9-6fef-4e34-8b58-48b1dd0dccd3)

Esse é um exemplo do formato que deve ficar o arquivo com os dados de conexão do banco (IP;TIPO;BANCO) sempre separado por ponto e virgula respectivamente e o mesmo formato para o arquivo com os dados de acesso ao banco (credenciais), (usuário;senha) também separados por ponto e virgula.

Em seguida na imagem é apresentado o script para a execução do backup caso o tipo do banco seja MySQL.
![image](https://github.com/user-attachments/assets/7177281c-7a3d-49e6-a96f-f051561a6b74)
